# Global parameters

# URLs and API keys for the different parts of the GTFS-R feed
# You should not change these unless a new version of the API is released
gtfs-feed-url: "https://www.transportforireland.ie/transitData/Data/GTFS_Realtime.zip"
gtfs-r-api-url: "https://api.nationaltransport.ie/gtfsr/v2/TripUpdates?format=json"

# You should change this one. Use the key you get from TFI when you register for GTFS-R access
gtfs-r-api_key: "API KEY GOES HERE"

# How often to refresh the display.
# It must be strictly larger than 60 because the GTFS-R API will throttle us otherwise
update-interval-seconds: 62

# Start a HTTP server emitting the current data as JSON or HTTP.
http-server: false

stops: [
  {
    # Route 15A
    stop_id: 1114,
    walk_time: 15,
    routes: ["15A"]
  },
  {
    # route 54A
    stop_id: 2410,
    walk_time: 9,
    routes: ["54A"]
  },
  {
    # route 9
    stop_id: 2438,
    walk_time: 15,
    routes: ["9"]
  }
]
  

